version: '1.0'
services:
  fast-api:
    image: fast-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - fastapi-data:/app/data
volumes:
  fastapi-data: 
